services:
  frontend:
    build: .
    ports:
      - '5173:80'

  backend:
    image: hussard-machine-backend:latest
    ports:
      - '8000:8000'
    environment:
      - DATABASE_URL=postgresql://user:password@postgres:5432/hussard_db
    depends_on:
      - postgres

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=hussard_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
